### ISSUE TITLE
Help with my Issues

### ISSUE THREAD

**Issue by DaRealJake** [jagrosh/Selfbot#11]
I have a Big issues
I installed Java 1.8 But i cant open it
![capture](https://cloud.githubusercontent.com/assets/25902361/23126090/bd3eacd4-f7a7-11e6-84d3-db336e1eab37.PNG)

**Comment by DaRealJake** [comment]
@jagrosh I need the bot please reply

**Comment by firey1** [comment]
ehhhhhhhhhhhhhhhhhhhhhhhhhhhh i dont **KNOW** how to fix it

**Comment by DaRealJake** [comment]
LOL Hes my friend Reply my Issues

**Comment by DaRealJake** [comment]
@jagrosh If you can change the Java Self Bot to NodeJS Self Bot Then Your AWESOME AND THANKS!!!!!

**Comment by Hemerythrin** [comment]
10/10 thread

**Comment by jagrosh** [comment]
The original issue can be fixed by setting up your Java Path (you can find several tutorials for how to do that by searching online).

No current plans to switch the bot to NodeJS.
