### ISSUE TITLE
Cant access the bot file.

### ISSUE THREAD

**Issue by Benjamin2800** [jagrosh/Selfbot#12]
When i start the run.bat it's saying that i it can't access the bot.jar file. 
Please help.

**Comment by Benjamin2800** [comment]
Error: Unable to access jarfile JSelfBot.jar

**Comment by jagrosh** [comment]
Trying creating a new folder, and putting both files inside (along with your config and emojis file if you have it)

**Comment by jagrosh** [comment]
Did this solve the issue?
