### ISSUE TITLE
self.list breaks with too many custom emotes

### ISSUE THREAD

**Issue by Druanae** [jagrosh/Selfbot#15]
Bot breaks when you add too many custom emotes due to character limit of messages:

![2017-04-08_23-25-14](https://cloud.githubusercontent.com/assets/22475536/24832900/a30a2b6a-1cb2-11e7-83aa-455135a5a218.gif)

![image](https://cloud.githubusercontent.com/assets/22475536/24832896/7fbf3146-1cb2-11e7-9fe8-a3c103f57fc8.png)

**Comment by jagrosh** [comment]
What version are you running (see the `help` command)

**Comment by Druanae** [comment]
Oh whoops. I was running 0.6
Updating to 0.7 fixed the issue
