### ISSUE TITLE
SelfBot is Patched bug

### ISSUE THREAD

**Issue by fluffydaniel10** [jagrosh/Selfbot#19]
https://gyazo.com/442996686150aba27bfa760c860830d0.png
dones't working now but going errors
discord is epic update

**Comment by jagrosh** [comment]
[Warning] and [Info] are simply that; warnings and bits of information. Those are nothing to be concerned about.

However, the [Fatal] is pretty clear, you are using an invalid or outdated token. Try getting a new one using the instructions found [here](https://github.com/jagrosh/Selfbot#setup), and if that still doesn't work, change your password (or enable/disable 2FA) and try those same steps again.

**Comment by jagrosh** [comment]
Did getting a new token fix the issue?
