### ISSUE TITLE
Not an issue but an idea

### ISSUE THREAD

**Issue by TNLzItalic** [jagrosh/Selfbot#2]
Maybe have it so other people can use the commands so you are pretty much the server bot

**Comment by Nenkai** [comment]
Yeaaaah no. Most of commands are mostly used for changing settings, and if anybody could eval.. 
That would result in making some sort of permission system, which isn't the point of a selfbot.

**Comment by jagrosh** [comment]
This will not be happening. The Discord Developers themselves have stated that the _only_ way selfbots are allowed is if they respond to the user's own account and no one else. If you want a server bot, consider using a public bot or writing/hosting your own on a bot account.

**Comment by TNLzItalic** [comment]
Okay but im still looking forward to future updates. Also maybe have google show multiple searches instead of one ;P

**Comment by jagrosh** [comment]
In a future update, I'll change it so that if you put a number as the first thing you're searching for, it will return that many results (up to 10 max probably)
No ETA because I am quite busy this and next week.

**Comment by jagrosh** [comment]
multiple google search results has been added as of version 0.3
for a prefix of `self.` the command to search for the top 5 results for "discord" would be:
`self.google 5 discord`
