### ISSUE TITLE
run.command doens't run

### ISSUE THREAD

**Issue by ItsPugle** [jagrosh/Selfbot#20]
Whenever I run the `run.command` file (I'm on macOS Sierra), I get presented with this:

![Command](https://img.itspugle.ga/j0u6s94gcq.png)

I have full read and write permissions for the file. Would it matter in which directory all the files are in? I moved them from Downloads to ~/Code/Discord Selfbot:

![File locations](https://img.itspugle.ga/zmw705f5wo.png)

(Sorry if this is a dumb question, I don't really know anything about this side of development)

**Comment by Phineas** [comment]
Try cd'ing to that directory & try `sudo ./run.command` or you can just plainly invoke it using `java -jar JSelfBot.jar`, etc

**Comment by ItsPaul69** [comment]
why the fuck is it Java. Java is shit. NodeJS pls kthx bai

**Comment by ItsPugle** [comment]
Using `java -jar JSelfBot.jar` worked! Thanks ❤️
