### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MeowMeowImACat** [jagrosh/Selfbot#22]
Is there a way to change the colour on the side from pink/purple to a different colour?
![image](https://cloud.githubusercontent.com/assets/29001865/26522210/2a19fe80-42f3-11e7-88a9-b816075876c6.png)

**Comment by TheMonitorLizard** [comment]
That color is dependent on your color on a server.
If you're in a DM it's normally just gray.
There is no way to change it currently.
