### ISSUE TITLE
Problem with steps

### ISSUE THREAD

**Issue by darkwolfXST** [jagrosh/Selfbot#23]
I am not able to find the "run.bat" file, was this removed? Or is this an issue? Or do I just need help with this

**Comment by darkwolfXST** [comment]
I probably need help, but if you want me to screenshot what I see then I can show you.

**Comment by jagrosh** [comment]
**Setup Guide links the Releases page**:
![setup](http://i.imgur.com/GM8TkM4.png)


**Releases page includes run.bat**:
![release](http://i.imgur.com/qWI7DDE.png)

**Comment by darkwolfXST** [comment]
Okay thanks, that was fast
