### ISSUE TITLE
Another Issue, relating to the run.bat 

### ISSUE THREAD

**Issue by darkwolfXST** [jagrosh/Selfbot#24]
So back again with another issue, now I've installed java and jdk, the source code, JSelfBot.jar, run.bat and run.command and I seem to have the same issue 
![image](https://cloud.githubusercontent.com/assets/14501483/26630644/f4d050f2-464a-11e7-8cfa-097fbae6e9a6.png) as provided with a screenshot of the run.bat
Any info would be great, I do believe as it is just me

**Comment by darkwolfXST** [comment]
Apologies for the second issue, I just get really stuck in these things

**Comment by OmgItzIsquidiOfficial** [comment]
Install java.

**Comment by darkwolfXST** [comment]
I have said and done that, perhaps you have not read what I've said

**Comment by jagrosh** [comment]
You do not have java installed correctly. The error you have (`'java' is not recognized as an internal or external command...`) means that your command line does not recognize `java`, which means it is not added to your PATH. You can find tutorials online about how to fix this; it is not an issue with the selfbot.
