### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Bluscream** [jagrosh/Selfbot#29]
I don't want to rush you but the last release was in april :)

**Comment by jagrosh** [comment]
https://github.com/jagrosh/Selfbot/releases/tag/0.8

**Comment by Bluscream** [comment]
Awesome, thank you. Did you update the dependencies too?

**Comment by shikhir-arora** [comment]
If you mean the JDA version, yeah he did. It was at `3.0.0_165` before and it is now updated to `3.1.1_212` which is quite helpful! 

(You can always run `Java.type("net.dv8tion.jda.core.JDAInfo").VERSION` with the Eval command to get the JDA Version) 👍

**Comment by Bluscream** [comment]
Thanks for the tip :3
