### ISSUE TITLE
Add Automator Script (.app) for macOS users to automatically open terminal and start selfbot.

### ISSUE THREAD

**Issue by jaspergreenham** [jagrosh/Selfbot#3]
Title says it all:
Add Automator Script (.app) for macOS users to automatically open terminal and start selfbot.

Here is the script I.... very quickly... made. Could be improved, but this is a good starting point:
[JSelfBot copy.app.zip](https://github.com/jagrosh/Selfbot/files/645165/JSelfBot.copy.app.zip)

Hope this can be added officially so macOS users can also have the automated selfbot experience!

JS (JG).

**Comment by jagrosh** [comment]
I think this may be a bit more than is needed. Can you (or anyone else with a Mac) test to see if this would be sufficient?
[run.zip](https://github.com/jagrosh/Selfbot/files/674230/run.zip)

**Comment by Hemerythrin** [comment]
The file you posted had the following issues:
- Windows line endings
- Incorrect JAR name (JSelfBot instead of JSelfbot)
- Command files run in the home directory, not the one the file is located in

Here's a fixed version:
```sh
#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
DIR="$( dirname "$SOURCE" )"
while [ -h "$SOURCE" ]
do
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
  DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd )"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

cd "$DIR"
java -jar JSelfbot.jar
```

**Comment by jagrosh** [comment]
Thanks @Hemerythrin! If you or someone can confirm that this runs correctly (it's just your code put in a run.command file; hopefully NP++'s line endings works correctly), I'll put it in the releases
[run.zip](https://github.com/jagrosh/Selfbot/files/674289/run.zip)

**Comment by Hemerythrin** [comment]
Yep, works! 👌

**Comment by jagrosh** [comment]
Wonderful! It is now on the [releases](https://github.com/jagrosh/Selfbot/releases) page and referenced in the README. Thanks!

**Comment by jaspergreenham** [comment]
@jagrosh Would really appreciate a lounge unban now. It's been a while and I will almost do ONLY seflbot talking if you unban.
