### ISSUE TITLE
[Request] Embed Color

### ISSUE THREAD

**Issue by kingryan2004** [jagrosh/Selfbot#33]
Selecting the color of the embed, if possible. Might now due to roles.

**Comment by jagrosh** [comment]
This is already possible; check out the `embed` command

**Comment by kingryan2004** [comment]
I see that, but selecting the actual color of the embed.

**Comment by jagrosh** [comment]
If you're talking about the color bar on the side, it's already possible.

**Comment by kingryan2004** [comment]
Ah, I'll see if I can find out how to do it. Currently, it just does the color of my role.

**Comment by jagrosh** [comment]
Just use the `embed` command with no arguments for it to show you what you can use.

**Comment by kingryan2004** [comment]
Ah, tysm.
