### ISSUE TITLE
Embed Colour

### ISSUE THREAD

**Issue by HADES999** [jagrosh/Selfbot#34]
Getting Default Embed Colour Pink How to change it

**Comment by jagrosh** [comment]
When using the embed command (`self.embed`) it provides you with a list of items you can include (if you don't provide any arguments). To use a color in your custom embed, include `{color:#HEX}` (replacing HEX with a hex code, like `AAFF99`; `self.embed {color:#AAFF99}`.

All other embeds (help, todo list, etc) use the same color as your role, and are not configurable)
