### ISSUE TITLE
Everything repeats 3 times....

### ISSUE THREAD

**Issue by mrfizzl3** [jagrosh/Selfbot#36]
Everytime I run a command it repeats 3 times. What did I do wrong?

**Comment by jagrosh** [comment]
You're running the bot 3 times

**Comment by mrfizzl3** [comment]
Hmm... the only window open is the command prompt opened by run.bat. How can I fix this?

**Comment by jagrosh** [comment]
I'm guessing you double-clicked the jar file; go into task manager and close all Java processes

**Comment by mrfizzl3** [comment]
Yep! That worked! Thanks!
