### ISSUE TITLE
Custom emotes?

### ISSUE THREAD

**Issue by XemeriusDev** [jagrosh/Selfbot#40]
I haven't understood how can I add a custom emote?

**Comment by spotlightishere** [comment]
I'm gonna assume `self.` is your selfbot's prefix here.

```
self.set myEmote text to replace
```

Then, to use the emote, just type `:myEmote:`. It'll convert, as shown below:
![Emote replaced](https://user-images.githubusercontent.com/10055256/28503217-fbf6a772-6fc7-11e7-8006-8aaecf87cdba.png)

You can list emotes by doing `self.list`.

Note that selfbot emotes aren't the same as custom emoji provided by say a global server or on the server itself. You could upload an image of an emote you'd like to use everywhere, grab the URL of the image and add that as an emote.

**Comment by jagrosh** [comment]
In addition to the guide above, I've now added a wiki page that should explain these: https://github.com/jagrosh/Selfbot/wiki/Emojis
