### ISSUE TITLE
No run.bat file.

### ISSUE THREAD

**Issue by ThisIsColt** [jagrosh/Selfbot#43]
I don't see a run.bat file.
Help?

**Comment by DavidTechnoboy** [comment]
did you download the stuff from the [releases page](https://github.com/jagrosh/Selfbot/releases/tag/0.9) ??

**Comment by ThisIsColt** [comment]
Yeah I forgot I had to do that lol.
I did it and it worked
________________________________

**Comment by wickedlizerd** [comment]
Awesome! Wanna mark the issue as closed?

**Comment by ThisIsColt** [comment]
Ye
