### ISSUE TITLE
Cannot find self.js

### ISSUE THREAD

**Issue by NoBODYcheats** [jagrosh/Selfbot#46]
Hi, i've recenlty downloanded this Discord SelfBot, but when im trying to run it, it's saying cannot find module ........Selfbot-master\src\jselfbot\entities\self.js
Can you help, or i didn't done something?

**Comment by jagrosh** [comment]
Uh, what.
1. This is java, not javascript, so we don't have .js files
2. If you have those folders, you downloaded the wrong thing. Don't download the source code, download the .jar from the releases page.
