### ISSUE TITLE
self.quote not working properly when done from one DM to another

### ISSUE THREAD

**Issue by IcePhantom22** [jagrosh/Selfbot#48]
Hi,
Quoting text from one DM to another DM does not work. You get some random quoted text from the DM you're posting the message to instead of where you copied it from. 
For example, let's say that I copied a message ID from DM A, posted it in DM B, but I got random quoted text from DM B rather than A.
I hope that there's a way to fix this in future updates.

**Comment by jagrosh** [comment]
Are you using the correct channel ID to reference the other DM channel (the DM channel ID is not the user's ID)

**Comment by IcePhantom22** [comment]
Yes, I've tried using both the DM ID and User ID. I keep getting a random quote with the latter ID being posted simply as it is right after the quote.

**Comment by jagrosh** [comment]
Can you see if this has been fixed as of the [latest release](https://github.com/jagrosh/Selfbot/releases/latest)?

**Comment by IcePhantom22** [comment]
It has been fixed.
