### ISSUE TITLE
Error with the JSelfBot.jar

### ISSUE THREAD

**Issue by Mohitc12** [jagrosh/Selfbot#50]
C:\Users\user\Desktop\New folder>java -jar JSelfBot.jar
Error: Unable to access jarfile JSelfBot.jar
Please help the JSelfbot.jar isn't working.

**Comment by vitalkanev** [comment]
Please download the correct files from [This page](https://github.com/jagrosh/Selfbot/releases) and ***NOT the source code archives or any `.java` files!!!***
