### ISSUE TITLE
Fatal RestActions

### ISSUE THREAD

**Issue by DelKatey** [jagrosh/Selfbot#51]
Hi, I got two fatal errors, of which I am not sure if anything should be done about it...

> [07:52:58] [Info] [Emojis]: Successfully loaded 7 custom emojis!
> [07:52:58] [Info] [Todo]: Successfully loaded 1 todo entries!
> [07:53:03] [Info] [JDA]: Login Successful!
> [07:53:04] [Info] [JDASocket]: Connected to WebSocket
> [07:54:40] [Info] [JDA]: Finished Loading!
> [07:54:40] [Info] [Selfbot]: Successfully logged in as <username>
> You are currently in 37 guilds!
> Type self.help in Discord to get started!
> [07:54:41] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message
> [07:54:41] [Fatal] [RestAction]: RestAction queue returned failure: [ErrorResponseException] 10008: Unknown Message

**Comment by jagrosh** [comment]
Those can be ignored, it's likely that you or a bot is deleting one of your own messages before the selfbot is able to.

**Comment by DelKatey** [comment]
Ah... Guess you can mark it as resolved or similar then, I deleted some of my own commands as the bot didn't seem to be responding at first.

Good to know it's not due to me fiddling around with stuff on the server it is on.
