### ISSUE TITLE
When I try to run.command on mac, it doesn't work and this shows up.

### ISSUE THREAD

**Issue by queencyka** [jagrosh/Selfbot#52]
How do I fix this?

<img width="584" alt="screen shot 2017-08-26 at 12 33 56 am" src="https://user-images.githubusercontent.com/31358124/29733680-09da8ef0-89f7-11e7-8ddb-fb5a165f28e9.png">

**Comment by jagrosh** [comment]
Did you try changing the access privileges like the warning suggested?
![warning](http://i.imgur.com/yygjUyO.png)

**Comment by queencyka** [comment]
<img width="142" alt="screen shot 2017-08-26 at 1 00 23 am" src="https://user-images.githubusercontent.com/31358124/29734289-fc575a8a-89f9-11e7-80b2-fb876a36fdfb.png">
Yes I did I tried to give the maximum privileges to everything but this is the most it allowed me to do. I don't know how else I can affect the privileges.

**Comment by jagrosh** [comment]
Hm, maybe try running from terminal.
Open terminal, navigate to the directory (`cd /path/to/folder`) and run `java -jar JSelfBot.jar`

**Comment by queencyka** [comment]
It kinda started working but now idk what's going on.
<img width="609" alt="screen shot 2017-08-26 at 1 17 15 am" src="https://user-images.githubusercontent.com/31358124/29734685-52fcb7c0-89fc-11e7-8c36-c00ed6a621dd.png">

**Comment by queencyka** [comment]
nevermind, it finally worked thank you!

**Comment by jagrosh** [comment]
Looks like some things related to channel categories, you can safely ignore those (unreleased features often cause warnings like those)

**Comment by spotlightishere** [comment]
My guess is probably because run.command has to be `chmod a+x`'d or anything similar to `.sh` files. A guess on how to fix this would create a repo with files like this since git preserves permissions to the best it can, but I don't know if downloading a zip from GitHub would preserve such permissions.
