### ISSUE TITLE
New Discord update

### ISSUE THREAD

**Issue by Osliah** [jagrosh/Selfbot#56]
Hey, yeah this like an enhancement but it's something that will need to be added due to it filling up the run as it doesn't know what to do. You need to add a category channel which it can recognise; an example of run - http://prntscr.com/gj1eoh and a category one etc http://prntscr.com/gj1fgf.

**Comment by TheMonitorLizard** [comment]
This is a library issue

**Comment by jagrosh** [comment]
Can you see if this is fixed as of [the latest release](https://github.com/jagrosh/Selfbot/releases/latest) and close this issue if it is fixed?
