### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by DracoZ12** [jagrosh/Selfbot#6]
I have an idea for the selfbot, Add more "embed" options, example, the command !imgembed http://image.com/img.png will send an embedded image, !avatar [Mention Or Id] Will give the avatar, !sayembed will do an fake quote.
Etc ....

**Comment by jagrosh** [comment]
you can do {image:http://image.url} to embed an image already
I will consider avatar functionality

**Comment by DracoZ12** [comment]
Oh, thanks ! :D

**Comment by jagrosh** [comment]
As of the most recent version, getting a user's avatar is a command, I think that will be sufficient if you want to do some custom embeds with that url.
