### ISSUE TITLE
Channel catagories need to be properly defined so the Self Bot doesn't error trying to see them as neither text nor voice channels

### ISSUE THREAD

**Issue by AdministratorReece** [jagrosh/Selfbot#60]
The add'n of channel categories has brought this issue up. I can't use the bot no more.

Would love a fix asap

**Comment by zochgcom** [comment]
the same happens to me!

**Comment by Slothiful** [comment]
Same issue here. Bot can't even start.

**Comment by jagrosh** [comment]
Can you see if this is fixed as of [the latest release](https://github.com/jagrosh/Selfbot/releases/latest) and close this issue if it is fixed?

**Comment by AdministratorReece** [comment]
Issue resolved. Thanks jagrosh.
