### ISSUE TITLE
Bot not accepting commands

### ISSUE THREAD

**Issue by redsauce117** [jagrosh/Selfbot#63]
When booting I get this fatal error, and the bot will not accept any commands issued by the user.
![image](https://user-images.githubusercontent.com/24428698/31747709-1f4771ee-b423-11e7-9ba7-f0c2fbb96900.png)

**Comment by jagrosh** [comment]
The bot is not fully loaded until you see a message in the console that says it is finished loading, and it won't respond to commands until it is finished loading. That error can be ignored and does not affect the loading of the bot.

**Comment by redsauce117** [comment]
Hmm. Alright i'll give it a few more minutes.
