### ISSUE TITLE
Suggestion: Add a warning about the Discord ToS to the top of the README.md

### ISSUE THREAD

**Issue by ItsPugle** [jagrosh/Selfbot#65]
Since selfbots are officially against the Discord ToS and will result in your account being moderated if reported, I suggest you add a disclaimer to the README.md.

**Comment by jagrosh** [comment]
There is already a disclaimer here, which links to the terms of service: https://github.com/jagrosh/Selfbot#final-notes

**Comment by ItsPugle** [comment]
It's at the very bottom... I mean at the top:
```markdown
# Selfbot
This is a simple Discord selfbot, written in Java using the [JDA](https://github.com/DV8FromTheWorld/JDA) library.

[![Setup](http://i.imgur.com/VvXYp5j.png)](#setup)

The use of selfbots is explicitly noted as a violation of the Discord Terms of Service. Use of selfbots is at your own risk, and can result in your account being terminated.
## Features
```
