### ISSUE TITLE
Auto sending of messages

### ISSUE THREAD

**Issue by EpicExcelsior** [jagrosh/Selfbot#67]
JSelfBot The self bot should have the ability to send messages for the person that it responds to. For example, someone could set a message to be sent every 30 seconds or 5 hours. Also, I would like this to work for messages that have spaces in them. (hello there)

**Comment by shikhir-arora** [comment]
That’s really pushing the limits of the already tight restrictions on Discord selfbots — such action is likely to get one banned if abused, which something like that can easily be.

**Comment by jagrosh** [comment]
This will not be added. The only features that are considered are features that the output occurs directly after the command is used; any automatic messages or actions will not be considered (and is likely to result in your account being banned as well).
