### ISSUE TITLE
Selfbot not working

### ISSUE THREAD

**Issue by RichardzPlayz** [jagrosh/Selfbot#69]
I wrote everything that I had to in config.txt, ran run.bat, and when I tried to do Ay.help, nothing came up.

**Comment by shikhir-arora** [comment]
Going to need more than just that. Do you have the right JDK and Java 8 installed? When you run the file what does it say?

**Comment by RichardzPlayz** [comment]
![screenshot_86](https://user-images.githubusercontent.com/34419868/33806347-29387e1e-ddc7-11e7-9191-b86230a6c38f.png)

**Comment by jagrosh** [comment]
It hasn't finished loading yet

**Comment by RichardzPlayz** [comment]
Does the cmd have to be open for the selfbot to work? Because I have it open, and it worked..

**Comment by jagrosh** [comment]
Yes, the Cmd window is running the selfbot, it needs to stay open; closing it shuts off the selfbot

**Comment by RichardzPlayz** [comment]
Ah, then problem solved.
