### ISSUE TITLE
Where do I find Todo List and Custom Emoji download?

### ISSUE THREAD

**Issue by RichardzPlayz** [jagrosh/Selfbot#70]
Where do I find Todo List and Custom Emoji download, jagrosh doesn't want to answer on discord, haha.

**Comment by jagrosh** [comment]
You don't download them, they are automatically generated when you use the emoji or todo features

**Comment by RichardzPlayz** [comment]
Oh? 
![screenshot_87](https://user-images.githubusercontent.com/34419868/33806448-b09f73e8-ddc8-11e7-8864-6407ea39f441.png)

**Comment by jagrosh** [comment]
Yes, if you add an item to your todo list, you'll see that the file was generated

**Comment by RichardzPlayz** [comment]
![screenshot_88](https://user-images.githubusercontent.com/34419868/33806464-e3bd126c-ddc8-11e7-97ac-5416b83d98d4.png)

**Comment by jagrosh** [comment]
you need to include your prefix just like you would with any other command

**Comment by RichardzPlayz** [comment]
Oh.
